### PR TITLE
 Tile Map for Assembly 

### PR DESCRIPTION
**Pull request by maciejmiklas**
Changes in Tile Map View:
1) Hide "Download Sprites" Section
2) Support for Tile Map containing palette offset for Assembly
3) Clean asks for Sprite/Palette ID to fill up empty Tile Map
4) Tolltips with help

Please correct my writing if you wish better to understand/grammar, especially in Tooltips/Help.

I've created videos showing how it works:
https://youtu.be/USjS0AyYe74
https://youtu.be/jdq_96o4WAg

Regards,
Maciej

### CODE REVIEW

**Comment by remy** [comment]
Ignore the build fail. I'm looking at your videos and the code. I think I should fix up the tilemap preview so it correctly reflects the palette used when placing the tile (otherwise I think it's a bit confusing), but this looks very useful and I'll try to merge it in as soon as I can 👍

**Comment by maciejmiklas** [comment]
If you make improvements, I will update my videos so we have a tutorial.

**Comment by remy** [comment]
@maciejmiklas I'm just working through the code, either making fixes on my side of things to support your change or to tweak bits you've contributed.

I've got one question for now - should the "Palette Reference" on the "Tile Map" tool only appear if *both* 4-bit is selected and 8px tiles is selected (i.e. it should not appear if 16px tiles are selected). Is that correct?

**Comment by remy** [comment]
Also, you made a UI change to the sprite editor tool - adding a dropdown for the palette. Was this because you didn't realise the palette ids were button/clickable?

SCR-20240320-uhsj-min

**Comment by remy** [comment]
Unrelated - I know why your sprite kept going blue when you cleared or reset the sprite stage. It's because the transparent index - for a 256 palette is 227. But when the 4 bit mode is enabled, you're picking from a 16 byte palette, so 227 becomes 3 (227 mod 16) and the index 3 palette colour is (usually) blue.

Not sure whether there's a sensible work around on that, but it did take me a while to understand why it was happening (so it's doing what we've told it to do, rather than being a bug).

**Comment by maciejmiklas** [comment]
I did not know Palette IDs were clickable, but I like this idea. The border around the numbers may help people recognize them as buttons. In such a case, the Sprite Editor should not have a dropdown, so both should be symmetrical. 

This blue background is not a problem at all.

**Comment by remy** [comment]
I've had to make a new PR from my work last night, I had hoped to add to this base, but I couldn't work out how to (though your commits are on the branch with your name): https://github.com/remy/zx-tools/pull/75

**Comment by maciejmiklas** [comment]
It does not matter how it get integrated, I just would like to use it for assembly :)

**Comment by remy** [comment]
Closing so we can work on the updated branch https://github.com/remy/zx-tools/pull/75

**Pull request closed without merging**
